### ISSUE TITLE
Cannot find module 'readline/promises'

### ISSUE THREAD

**Issue by coixseeds** [connertennery/Notion-to-Obsidian-Converter#24] opened 2022-04-12 03:21 UTC
Hello! 

Thank you for creating this script, it will help me with my database relocation from Notion to Obsidian.

Not sure what is happening but I am getting the following message:

```
Error: Cannot find module 'readline/promises'
Require stack:
- C:\Notion-to-Obsidian-Converter-main\main.js
←[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:778:27)←[39m
←[90m    at Module.require (node:internal/modules/cjs/loader:1005:19)←[39m
←[90m    at require (node:internal/modules/cjs/helpers:102:18)←[39m
    at Object.<anonymous> (C:\Notion-to-Obsidian-Converter-main\main.js:2:18)
←[90m    at Module._compile (node:internal/modules/cjs/loader:1103:14)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:981:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [ ←[32m'C:\\Notion-to-Obsidian-Converter-main\\main.js'←[39m ]
}

```
Can you please help?

Thanks!
Leo

**Comment by connertennery** [comment] 2022-04-12 03:24
Hi @coixseeds!
Would you mind running `node --version` in your terminal and letting me know what version you have?

Thank you!

**Comment by coixseeds** [comment] 2022-04-12 15:46
Hi Conner!

My version is v16.14.2. Let me know if you need more information.

Thank you,

**Comment by Envoy-VC** [comment] 2022-04-23 17:03
Hi I also have the same Issue My node version is 16.14.22

**Comment by connertennery** [comment] 2022-04-26 15:55
Hi everyone! Sorry for the delay. The issue is that I used a Node module that was too new.

The problem can be fixed by updating Node to latest, or by using nvm (or nvm-windows) to manage multiple Node versions if you need to continue to have LTS on your computer.

I’ll try to address the problem as soon as I can and rewrite it to work for LTS instead of using latest. Work is a bit hectic so my time is limited but it should be a fairly simple fix.

Thank you for your comments!

**Closed** 2022-04-27 04:21 UTC

**Comment by connertennery** [comment] 2022-04-27 04:24
@coixseeds @uzihaq @Envoy-VC 

Thanks again! I removed async/await code and verified that it works on Node's current LTS (16.15.0).

This should work for you all, but if you are experiencing issues, please update Node if you can. The current LTS is 16.15.10 and you're all behind that. The latest version is Node 18.0.0, but I know that not everyone can use the latest version.

I hope this resolves any issues you have! I'll try to ensure I'm working from LTS from now on.
